version: "3.8"
services:
    db:
        container_name: ai_ice_db
        build:
            context: .
            dockerfile: Dockerfile.pgvector
        networks:
            - fiscalnoteai
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"

    filechat:
        container_name: filechat
        build: .
        ports:
            - "8081:8080"
        networks:
            - fiscalnoteai
        environment:
            OPENAI_API_KEY: ${OPENAI_API_KEY}
            PGVECTOR_CONNECTION: postgresql+psycopg2://postgres:postgres@db:5432/documents
        depends_on:
            - db
        volumes:
            - .:/usr/src/app

networks:
    fiscalnoteai:
        name: fiscalnoteai
